name: 'action yml'
description: 'dotnet restore'
inputs:
  project_path:  
    description: 'path'
    required: true
  project_configuration:  
    description: 'test-path'
    required: true
  output_path:  
    description: 'newTag'
    required: true  
  ssis_action:  
    description: 'newTag'
    required: true
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: |
        $Env:PATH += ";C:\Program Files (x86)\Microsoft Visual Studio\Installer"
        $VS_FILE = vswhere -products * -format json | jq '.[0]' | jq .productPath
        $TMP = Split-Path -Path $VS_FILE.replace('\\', '\')
        $VS_PATH = $TMP.replace('"', '')
        $Env:PATH += ";$VS_PATH"
        Get-ChildItem -Path ${{ inputs.project_path }} -Filter *.dtproj -Recurse -File -Name| ForEach-Object {

          devenv $_ /build Development /Project $_

        }
        C:\Windows\System32\robocopy.exe D:\TFS_BUILD\Working\13\s\BulkUploadPackages\bin\Development D:\TFS_BUILD\Working\13\a /s /r:10
      shell: powershell
      if: ${{ inputs.ssis_action == 'build' }}
